### ISSUE TITLE
ERROR: You need to provide an output directory through --out option. Exit

### ISSUE THREAD

**Issue by amodvet** [mquinodo/AutoMap-nonhuman#1]
Hi Dr Quinodoz,
I am using AutoMap for nonhuman data and I am facing this error:
Command: bash AutoMap_v1.2_nonhuman.sh --multivcf A.vcf --out /home/amod/Desktop/Viz
Output of this command:
# bcftools higher or equal to v1.9
# bedtools higher or equal to v2.24.0
# perl higher or equal to v5.22.0
# R higher or equal to v3.2.0
## ERROR: You need to provide an output directory through --out option. Exit.
Could you please help me to solve this problem.

**Comment by mquinodo** [comment]
Hi,
Are you sure that /home/amod/Desktop is an existing path and that A.vcf is located where you launch the command?
Best,
Mathieu

**Comment by amodvet** [comment]
Yes Mathieu, my A.vcf file is located in the same folder where I kept AutoMap_v1.2_nonhuman.sh file and I also provided the path of same folder in --out flag.
I was using gvcf file, now I converted into vcf and used it as input file: 
The output of command was:
#bcftools higher or equal to v1.9
#bedtools higher or equal to v2.24.0
#perl higher or equal to v5.22.0
#R higher or equal to v3.2.0
##Parameters used by default:
 -> No use of --DP option, value set as default: 8
 -> No use of --binomial option, value set as default: 0.000001
 -> No use of --percaltlow option, value set as default: 0.25
 -> No use of --percalthigh option, value set as default: 0.75
 -> No use of --window option, value set as default: 7
 -> No use of --windowthres option, value set as default: 5
 -> No use of --minsize option, value set as default: 1
 -> No use of --minvar option, value set as default: 25
 -> No use of --minperc option, value set as default: 88
 -> No use of --maxgap option, value set as default: 10
 -> Homozygosity regions will be extended to nearest variant with maximum of 1 Mb.
##WARNING: No sample name provided through --id option, name will be taken from the VCF: 01001
1) Parsing of VCF file and variant filtering
 * 7989568 variants before filtering
grep: /home/amod/Desktop/Viz/01001/01001.clean.tsv: No such file or directory
## ERROR: Less than 10,000 variants with good quality detected (only 0 passing QC). Exit.

Even I am using TestSample.vcf file, The output was:
) Parsing of VCF file and variant filtering
 * 111569 variants before filtering
grep: /home/amod/Desktop/Viz/TestSample/TestSample.clean.tsv: No such file or directory
##ERROR: Less than 10,000 variants with good quality detected (only 0 passing QC). Exit

please help me out.

**Comment by mquinodo** [comment]
I apologise for the late answer.
Could you share the VCF so I can have a closer look for debug?
My email is mathieu.quinodoz@iob.ch
Best,
Mathieu
