### ISSUE TITLE
Test files originate from v1.0 although current version is v1.2

### ISSUE THREAD

**Issue by JNisk** [mquinodo/AutoMap-nonhuman#2]
Hello,

I was testing AutoMap and ran a test command as instructed in README:

`./AutoMap_v1.2_nonhuman.sh --vcf Test/TestSample.vcf --out Results-test`

which produced the following output file:

```
tail Results-test/TestSample/TestSample.HomRegions.tsv
chr20   10032276        16475222        6.44    56      96.43
chr20   18021738        19654878        1.63    53      92.45
chr21   27348563        30830311        3.48    60      90.00
chr22   17039174        18667677        1.63    106     97.17
chr22   18864233        20291427        1.43    80      97.50
chr22   36983525        39626061        2.64    199     95.48
## INFO: 357.8 Mb are in Homozygous Regions
## AutoMap v1.2 used for analysis
## Variant filtering parameters used: DP=8, percaltlow=0.25, percalthigh=0.75, binomial=0.000001, maxgap=10
## Other parameters used: window=7, windowthres=5, minsize=1, minvar=25, minperc=88, chrX=No, extend=1
```

The footer lines state that this file was generated with AutoMap v1.2. To compare with the expected results, I looked at the files in the Test folder:

```
tail Test/Test.HomRegions_correct.tsv
chr20   10032276        17416704        7.38    50      92.00
chr20   18005904        19673793        1.67    40      95.00
chr21   27348563        30969883        3.62    53      92.45
chr22   17038906        18667677        1.63    87      97.70
chr22   18864233        20291427        1.43    71      98.59
chr22   36983525        39626061        2.64    152     95.39
## INFO: 351.6 Mb are in Homozygous Regions (autosomal chromosomes)
## AutoMap v1.0 used for analysis
## Variant filtering parameters used: DP=8, percaltlow=0.25, percalthigh=0.75, binomial=0.000001, maxgap=10
## Other parameters used: window=7, windowthres=5, minsize=1, minvar=25, minperc=88, chrX=No, extend=1
```

The footer lines here state that this file was generated with v1.0. Also, the length of the detected homozygous regions (351.6 Mb) differs from the freshly generated results from v1.2 (357.8 Mb).

My question here is: should the files included in the Test folder perhaps be updated to match v1.2? In this state, I cannot be sure that my downloaded copy of the script works correctly. I would greatly appreciate your help, as this software seems very useful and I am aiming to implement it in my analysis pipeline.

**Comment by mquinodo** [comment]
Hello,

I apologise for the late answer.
Thank you for reporting the issue. I now corrected to output of the examples.
It was correct when you run it.

Kind regards.
