### ISSUE TITLE
AutoMap_v1.2_nonhuman.sh: line 289: $here.log: ambiguous redirect

### ISSUE THREAD

**Issue by Somatogenomics** [mquinodo/AutoMap-nonhuman#4]
I got the following error after running the script.

grep: wptslFF26EC.filtered.snp: No such file or directory
AutoMap_v1.2_nonhuman.sh: line 289: $here.log: ambiguous redirect
## ERROR: The input VCF format is incorrect ('bcftools query -l' was unsuccessful). Exit.

The file was and is currently in the present folder where I was running the script. The sample name is wptslFF26EC.filtered.snp.vcf

Any help towards fixing the problem would be greatly appreciated.

**Comment by mquinodo** [comment]
Could you share how you are calling the script like:
bash AutoMap_v1.2_nonhuman.sh --vcf VCF_file --out output_directory [other options]

Thank you

**Comment by ramikheireddine** [comment]
I am having the same issue, This is the the script:
bash AutoMap_v1.2_nonhuman.sh --vcf Routput_raw_variants.vcf --out Routput_directory 

The error:
AutoMap_v1.2_nonhuman.sh: line 289: /home/databench.log: Permission denied
## ERROR: The input VCF format is incorrect ('bcftools query -l' was unsuccessful). Exit.

**Comment by mquinodo** [comment]
It seems that you don't have write rights were you are executing the script. You can try to run it from a place where you have all rights.
